### PR TITLE
Use the `@actions/http-client` and `@actions/github` modules for proxy support

### LINKED ISSUE #112: Needs proxy support
For self-hosted runners that require a proxy, the Axios calls currently fail. I've proved out the PR here: https://github.com/actions/deploy-pages/pull/111

Please consider reviewing/merging it, or adding some other way to allow proxy input options.

Thanks!

### PR DESCRIPTION
**Pull request by JamesMGreene**
Fixes #112 
Closes #128 
Closes #111 
Closes #106

Shout out to @daleyjem / @jeremy-daley-kr for reporting the issue, proposing a PR, discussing approaches, and _hopefully_ also being up for testing this branch out...? 😁🤞🏻🙏🏻 

**TODO:**
- [x] Update the unit tests to get them passing
- [x] Manual regression testing
  - 🔐 See logs for https://github.com/paper-spa/starter-test-gatsby/actions/runs/4350617722/jobs/7601515477

### CODE REVIEW

**Comment by JamesMGreene** [comment]
@jeremy-daley-kr If you could verify the needed proxy support with this branch, that would be amazing! ❤️ 

```yaml
        uses: actions/deploy-pages@actions-http-client
```

File: src/deployment.js [hunk 1]
```diff
@@ -35,48 +39,33 @@ class Deployment {
...
       })
-      this.requestedDeployment = true
-      core.info(`Created deployment for ${this.buildVersion}`)
-      if (response && response.data) {
-        core.info(JSON.stringify(response.data))
-        this.deploymentInfo = response.data
+      this.deploymentInfo = {
+        ...deployment,
+        id: deployment?.['status_url']?.split('/')?.pop() || this.buildVersion,
+        pending: true
```
Comment (TooManyBees) [inline src/deployment.js:60]: Does it matter that in the previous version we only set `this.deploymentInfo` when `response.data` is present, and in this version we set it all the time with possibly undefined values?

File: src/deployment.js [hunk 2]
```diff
@@ -109,63 +99,63 @@ class Deployment {
...
+        let res = await getPagesDeploymentStatus({
+          githubToken: this.githubToken,
+          deploymentId
         })
 
-        if (res.data.status == 'succeed') {
+        if (res.data.status === 'succeed') {
           core.info('Reported success!')
           core.setOutput('status', 'succeed')
+          if (this.deploymentInfo) {
```
Comment (TooManyBees) [inline src/deployment.js:128]: this is always truthy, thanks to line 57

File: src/deployment.js (hunk 1 above)
Comment (JamesMGreene) [reply src/deployment.js:60]: With Octokit, we should always have `response.data` (as `deployment`, in this case) when the request returns successfully. Error (`>= 400` status code) responses should result in the Promise being rejected and hitting the `catch` logic branch.

https://github.com/octokit/request.js/blob/b432f47bdd456d3806e24378caba6ac889cb7d72/src/fetch-wrapper.ts#L102-L116

AFAIK, that was also true of Axios, so I'm not 100% on the exact choices (probably misunderstanding or caution 🤷🏻) that went into the previously used logic here.

File: src/deployment.js (hunk 2 above)
Comment (JamesMGreene) [reply src/deployment.js:128]: So long as the methods are call in the intended order. 😅  Less of a concern for the status check but I picture a future where we invoke `cancel()` potentially in a post-step if the workflow run fails or is canceled or something that may need to be able to operate without `this.deploymentInfo`. We're not there today, though, so your point is definitely valid. 👍🏻

**Comment by jeremy-daley-kr** [comment]
@JamesMGreene I'm getting this when I target your branch...

image

`Error: TypeError: octokit.rest.repos.createPagesDeployment is not a function`

**Comment by JamesMGreene** [comment]
@jeremy-daley-kr Ah, my bad. 🤦🏻‍♂️  I've updated to use `octokit.request` like you suggested, so please feel free to give it another try when you get a chance.

**Comment by jeremy-daley-kr** [comment]
@JamesMGreene Definitely getting there, but now I've got this:
image

**Comment by jeremy-daley-kr** [comment]
I think the page itself deployed. Maybe some optional chaining would get me further along to fill you in with more details?

**Comment by jeremy-daley-kr** [comment]
> Thanks for the feedback, @jeremy-daley-kr! Sorry it didn't go smoothly. 😖
> 
> I'll find some time to do further testing on our side before I ask you to check again. 😅

No worries, man. I appreciate you sticking with it. I realize it's a bit harder to test if not behind a proxy yourself. If Github had a way of pairing, I'd just as soon do that.

All I need to do at this point is just re-run the failed job since it pulls the latest from your branch, so just let me know.

**Comment by JamesMGreene** [comment]
@jeremy-daley-kr Can you give this another try? I think I've worked out the kinks now. 🤞🏻 😅

File: src/deployment.js (hunk 1 above)
Comment (tcbyrd) [reply src/deployment.js:68]: I'm going with caution, mainly because we're not in TS land and `response.data` could be undefined if some internal method doesn't create `response` properly. Not saying we need to change this, but I think that's why it was written that way.

File: src/deployment.js [hunk 3]
```diff
@@ -33,50 +45,35 @@ class Deployment {
...
+        pending: true
       }
+
+      core.info(`Created deployment for ${this.buildVersion}, ID: ${this.deploymentInfo.id}`)
+      core.debug(JSON.stringify(deployment))
+
+      return deployment
     } catch (error) {
-      core.info(error.stack)
+      core.error(error.stack)
```
Comment (tcbyrd) [inline src/deployment.js:76]: does `core.error` show up only on failed builds? I can't remember, but I feel like there was a reason we used `.info` on this catch block.

**Review by tcbyrd — APPROVED** [review]
LGTM. Just a few comments, but nothing blocking.

File: src/api-client.js [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+
+  try {
+    core.info(`Artifact exchange URL: ${artifactExchangeUrl}`)
+    const response = await httpClient.getJson(artifactExchangeUrl, {
+      Authorization: `Bearer ${runtimeToken}`
+    })
+
+    data = response?.result
+    core.debug(JSON.stringify(data))
+  } catch (error) {
```
Comment (TooManyBees) [inline src/api-client.js:23]: According to the [actions/http-client](https://www.npmjs.com/package/@actions/http-client#user-content-errors), it doesn't raise exceptions on non-success HTTP statuses like axios or octokit does.

Comment (JamesMGreene) [reply src/api-client.js:23]: Ooo, good catch! 😬

File: src/deployment.js (hunk 3 above)
Comment (JamesMGreene) [reply src/deployment.js:76]: The only one I was aware of that gets hidden by default was `core.debug` but I'll check with the Actions team on this one. Thanks for the call out!

Comment (JamesMGreene) [reply src/deployment.js:76]: Verified:

> `core.error` should show up on all builds regardless of the job failing or succeeding. And it's only an annotation, it doesn't actually set the conclusion of the job to failed, that's what `core.setFailed` is for: https://github.com/actions/toolkit/tree/main/packages/core#logging

File: src/deployment.js (hunk 1 above)
Comment (JamesMGreene) [reply src/deployment.js:68]: Eh, putting it back in doesn't really add any cognitive overhead, so playing it safe makes sense. 👍🏻

**Comment by jeremy-daley-kr** [comment]
> @jeremy-daley-kr Can you give this another try? I think I've worked out the kinks now. 🤞🏻 😅

All Green on my end! Boom! 🤜💥🤛

**Review by jeremy-daley-kr — APPROVED** [review]
Excellent work, and thank you!

**Comment by JamesMGreene** [comment]
Awwwwwesome! 🎉 

I'll work out the last few issues that my teammates have called out and try to get this shipped later today. 🚀

File: src/api-client.js (hunk 4 above)
Comment (JamesMGreene) [reply src/api-client.js:23]: Turns out that's only _partially_ true. 😅 

Using `getJson` instead of `get` actually adds the potential for rejecting with an `HttpClientError` but it isn't consistent enough for my taste. I'm going to switch to use `get` instead of `getJson`, which _will_ let us have full control over the error handling (since it does none 😜).

File: src/api-client.js [hunk 5]
```diff
@@ -0,0 +1,172 @@
...
+  if (data != null && 'message' in data) {
+    if (Array.isArray(data.errors)) {
+      return `${data.message}: ${data.errors.map(JSON.stringify).join(', ')}`
+    }
+    return data.message
+  }
+
+  // Defer back to the caller
+  return null
+}
```
Comment (JamesMGreene) [inline src/api-client.js:24]: Probably unnecessary since we're working with the Runtime API rather than the GitHub API here. 🤔

File: src/deployment.js (hunk 1 above)
Comment (JamesMGreene) [reply src/deployment.js]: Added an `if` condition back in for this. 👍🏻

**Comment by JamesMGreene** [comment]
Was able to use this branch to successfully deploy all of our Pages starter workflow regression testing repos. 👍🏻

**Comment by JamesMGreene** [comment]
Published as part of the `v1.2.5` release! 🚀 

Any of the following `uses` statements should work:

```
uses: actions/deploy-pages@v1
uses: actions/deploy-pages@v1.2.5
uses: actions/deploy-pages@497da40f5225e762159b457c9ae5d6f75a136f5c
```
